if (typeof translations == 'undefined') {
    translations = {};
}

translations.zh_CN = {
    'permName.PERM_VIEW_ACCOUNT_COLLECTION': '查看所有账号',
    'permName.PERM_ADD_ACCOUNT': '添加账号',
    'permName.PERM_VIEW_ACCOUNT': '查看账号',
    'permName.PERM_EDIT_ACCOUNT': '编辑账号',
    'permName.PERM_LOCK_ACCOUNT': '删除账号',
    'permName.PERM_UNLOCK_ACCOUNT': '恢复账号',
    'permName.PERM_VIEW_ROLE': '查看所有角色',
    'permName.PERM_ADD_ROLE': '添加角色',
    'permName.PERM_EDIT_ROLE': '编辑角色',
    'permName.PERM_LOCK_ROLE': '删除角色',
    'permName.PERM_UNLOCK_ROLE': '恢复角色',
    'permName.PERM_ASSIGN_PERMISSION': '分配权限',
    'permName.PERM_VIEW_PERMISSION': '查看权限',
    'permName.PERM_EDIT_PERMISSION': '编辑权限',
    'permName.PERM_COMPLETE_CERTIFICATE': '完善认证信息',

    'permName.PERM_VIEW_PRODUCT_COLLECTION': '产品列表查询',
    'permName.PERM_ADD_PRODUCT': '添加产品',
    'permName.PERM_VIEW_PRODUCT': '产品详情',
    'permName.PERM_EDIT_PRODUCT': '编辑产品',
    'permName.PERM_DELETE_PRODUCT': '删除产品',
    'permName.PERM_DELETE_HOT_PRODUCT': '删除热门产品',
    'permName.PERM_VIEW_PRODUCT_PRICE': '获取产品报价',
    'permName.PERM_DELETE_PRODUCT_PRICE': '删除产品报价',
    'permName.PERM_NO_PRODUCT_PRICE_ENTERPRISE': '未报价的企业列表',
    'permName.PERM_PRODUCT_ES': '产品重建索引',
    'permName.PERM_PRODUCT_PRICE_ES': '产品报价重建索引',
    'permName.PERM_HOT_PRODUCT_TYPES': '热门产品分类',
    'permName.PERM_ADD_HOT_PRODUCT': '添加热门产品',
    'permName.PERM_RESTORE_HOT_PRODUCT': '重置热门产品',
    'permName.PERM_VIEW_HOT_PRODUCT': '查询热门产品',
    'permName.PERM_SORT_HOT_PRODUCT': '热门产品排序',
    'permName.PERM_VIEW_ALIASES': '索引列表',
    'permName.PERM_UPDATE_ALIASES': '修改别名',
    'permName.PERM_ADD_ALIASES': '添加别名',
    'permName.PERM_ADD_CATEGORY': '添加分类',
    'permName.PERM_VIEW_CATEGORY': '分类详情',
    'permName.PERM_VIEW_CATEGORY_COLLECTION': '分类列表',
    'permName.PERM_VIEW_PROPERTY': '属性详情',
    'permName.PERM_ADD_HOT_CATEGORY': '添加热门分类',
    'permName.PERM_VIEW_ALL_CATEGORY': '所有分类',
    'permName.PERM_VIEW_HOT_CATEGORY': '热门分类详情',
    'permName.PERM_VIEW_IMPORT_CATEGORY': '导入分类',
    'permName.PERM_VIEW_IMPORT_CATEGORY_PROPERTIES': '导入分类属性',
    'permName.PERM_VIEW_IMPORT_CATEGORY_PROPERTIES_ES': '分类和属性导入ES',
    'permName.PERM_VIEW_IMPORT_ALL_CATEGORY_ES': '所有分类导入ES',
    'permName.PERM_VIEW_UPLOAD_TOKEN': '获取七牛上传token',
    'permName.PERM_DELETE_RESOURCE': '删除七牛资源',
    'permName.PERM_IMPORT_CREDIT_TYPE': '导入认证类型',
    'permName.PERM_IMPORT_AREA': '导入省市区',
    'permName.PERM_VIEW_ENTERPRISE_COLLECTION': '获取企业列表',
    'permName.PERM_VIEW_ENTERPRISE': '获取企业详情',
    'permName.PERM_EDIT_ENTERPRISE': '编辑企业',
    'permName.PERM_DELETE_ENTERPRISE': '删除企业',
    'permName.PERM_ADD_ENTERPRISE': '添加企业',
    'permName.PERM_ADD_ENTERPRISE_COMMENT': '添加企业评论',

    'permName.PERM_VIEW_USER_COLLECTION': '获取用户列表',
    'permName.PERM_ADD_USER': '添加用户',
    'permName.PERM_VIEW_USER': '用户详情',
    'permName.PERM_EDIT_USER': '编辑用户',
    'permName.PERM_DEACTIVATE_USER': '删除用户',
    'permName.PERM_ACTIVATE_USER': '激活用户',
    'permName.PERM_LOCK_USER': '锁定用户',
    'permName.PERM_UNLOCK_USER': '解锁用户',

    'permName.PERM_ENTERPRISE_PRICE_REQUIREMENT':'供应商投标',
    'permName.PERM_ENTERPRISE_VIEW_REQUIREMENT':'供应商配单列表',
    'permName.PERM_ENTERPRISE_BID_INFO_REQUIREMENT':'供应商查看配单信息',
    'permName.PERM_ENTERPRISE_VIEW_ONE_REQUIREMENT': '供应商查看某一需求信息',
    'permName.PERM_ENTERPRISE_ORDER_REQUIREMENT': '供应商生成订单',
    'permName.PERM_MODIANLI_MATCH_REQUIREMENT':'魔电手动配单',
    'permName.PERM_MODIANLI_SHELF_REQUIREMENT':'魔电上下架',
    'permName.PERM_MODIANLI_VIEW_ONE_REQUIREMENT':'魔电查看某一需求',
    'permName.PERM_MODIANLI_VIEW_ONE_BIDDING_REQUIREMENT':'魔电查看某一需求的配单',
    'permName.PERM_MODIANLI_VALIDATE_REQUIREMENT':'魔电审核',
    'permName.PERM_MODIANLI_VIEW_REQUIREMENT':'魔电需求列表',
    'permName.PERM_PROFILE_ADD_REQUIREMENT':'企业新增需求',
    'permName.PERM_PROFILE_CERT_ADD_REQUIREMENT':'企业认证状态',
    'permName.PERM_PROFILE_PAGE_VIEW_REQUIREMENT':'企业发布需求列表',
    'permName.PERM_PROFILE_BID_REQUIREMENT':'企业选择供应商',

    'permName.PERM_DELETE_PRERENDERS':'删除所有的预渲染',
    'permName.PERM_DELETE_LIST_PAGE':'删除预渲染列表'

}