version: '3'
services:
  api:
    image: md-api:latest
    container_name: api
    external_links:
      - redis:redis
      - mysql:mysql
      - es:es
      - rabbit:rabbit
    volumes:
      - /data/logs:/data/logs
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    networks:
      - server_mdnet

networks:
  server_mdnet:
    external: true