version: '3'
services:
  broker:
    image: md-job:latest
    container_name: job
    external_links:
      - redis:redis
      - mysql:mysql
      - es:es
      - rabbit:rabbit
    volumes:
      - /data/logs:/data/logs
    ports:
      - "127.0.0.1:8085:8085"
    restart: always
    networks:
      - server_mdnet


networks:
  server_mdnet:
    external: true