spring:
  profiles:
    active: #spring.profiles.active#
  freemarker:
    cache: true
    charset: UTF-8
    enabled: false
spring.session.redis.flush-mode: on_save
spring.session.store-type: redis
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
flyway:
  baseline-on-migrate: true
power:
  static:
    img: http://static.modianli.com/portal/2017/05/image/1494918060205.jpg




